services:
  postgres:
    image: postgres:14.3-alpine
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projeto1
    ports:
      - 5428:5432
