server:
  port: 9090
  servlet:
    context-path: /projeto1

spring:
  application:
    name: projeto1

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5429/projeto1
    driver-class-anem: org.postgresql.Driver

  jpa:
    hibernate:
    ddl-auto: disable
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enable: true
    locations: classpath:db/migration
    basaeline-on-migrate: true
